orders/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^cart_adding/$', views.cart_adding, name='cart_adding'),
    url(r'^checkout/$', views.checkout, name='checkout'),
]

products/urls.py
from django.conf.urls import url, include
from products import views


urlpatterns = [
    url(r'^products/', views.products, name='products'),
    url(r'^product/(?P<product_id>\w+)/$', views.product, name='product'),
]

untitled/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    url(r'^', include('products.urls')),
    url(r'^', include('orders.urls')),
] \

products/models.py
from django.db import models


# class ProductCategory(models.Model):
#     name = models.CharField(max_length=64, blank=True, null=True, default=None)
#     is_active = models.BooleanField(default=True)
#
#     def __str__(self):
#         return "%s" % self.name
#
#     class Meta:
#         verbose_name = 'Категория товара'
#         verbose_name_plural = 'Категория товаров'
#

class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    price = models.IntegerField(default=0)
    discount = models.IntegerField(default=0)
    # category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None)
    # short_description = models.TextField(blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s, %s" % (self.price, self.name)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None)
    image = models.ImageField(upload_to='static/media/products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

products/forms.py
from django import forms
from .models import *

# class orderform(forms.ModelForm):
#
#     class Meta:
#         model = order
#         exclude = [""]
#
#

products/views.py
from django.shortcuts import render
from products.models import *


def products(request):
    products = ProductImage.objects.filter(is_active=True, is_main=True)
    return render(request, 'products/products.html', locals())


def product(request, product_id):
    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    print("ss = ", request.session.session_key)
    product = Product.objects.get(id=product_id)
    return render(request, 'products/product.html', locals())

templates/products/product.html
{% extends 'base.html' %}
{%  load static %}
{% block content %}
    <div class="product_single">
        <div class="product_view_single">
            {% for image_item in product.productimage_set.all %}
                <img class="product_img" src="/{{ image_item.image.url }}">
            {% endfor %}
        </div>
        <div id="settings" class="settingsWindow">
             <form class="action" method="post" id="settings_form" action="{% url 'cart_adding' %}">
                 {% csrf_token %}

                 <h2 class="product_header">
                    {{ product.name }} <br>
                    {{ product.price }}<span> Rub</span>
                 </h2>
                  <div class="top_area">
                      <ul>
                        <li>
                            <div class="settings_block">
                                    <span >Материал</span><br>
                                    <input type="radio" name="veins" value="Kantal 0.4" checked="checked" />
                                    <span>Kantal 0.4</span><br>
                                    <input type="radio" name="veins" value="SS 0.4" />
                                    <span>Stanless 0.4</span>
                            </div>
                        </li>
                          <li>
                            <div class="settings_block">
                                    <span>Обмотка</span><br>
                                    <input type="radio" name="winding" value="NiC 0.1" checked="checked">
                                    <span>Nichrome 0.1</span><br>
                                    <input type="radio" name="winding" value="NiC 0.2">
                                    <span>Nichrome 0.2</span><br>

                            </div>
                          </li>
                          <li>
                            <div class="settings_block">
                                    <label for="coil">Колличество витков</label>
                                    <select id="coil" name="coil">
                                            <option>3</option>
                                            <option>4</option>
                                            <option>5</option>
                                            <option>6</option>
                                            <option>7</option>
                                            <option>8</option>
                                    </select>
                            </div>
                          </li>
                          <li>
                            <div class="settings_block number">
                                <label for="nmb">Колличество койлов</label>
                                <select id="nmb" name="nmb">
                                            <option>2</option>
                                            <option>4</option>
                                            <option>6</option>
                                            <option>8</option>
                                            <option>10</option>
                                    </select>
                            </div>
                          </li>
                   </ul>
                </div>

                <div class="button_area">
                        <button class="submit" id="buy_button"
                           data-product_id="{{ product.id }}" data-product_name="{{ product.name }}"
                                data-product_price="{{ product.price }}">В корзину</button>

                </div>
            </form>
        </div>
        <div class="description">
            <span class="description_head">Описание</span>
            {{ product.description }}
        </div>
    </div>

{% endblock %}

templates/products/products.html
<head>
    <title>Товары</title>
</head>

{% extends 'base.html' %}
{%  load static %}



{% block content %}
    <ul class="product">
        {% for item in products %}
            <li class="product_item">
                <div class="product_view">
                    <img class="product_img" src="/{{ item.image.url }}">
                </div>
                <div class="product_desc">
                    <h2 class="product_header">
                        {{ item.product.name }}
                    </h2>
                    {{ item.product.description }}
                </div>
                <div class="product_price">
                    {#сюда настройка койлов#}
                    <a href="">
                        <div class="price_wrap">
                            <div class="price_amount">
                                <span class="amount">{{ item.product.price }}</span>
                                <span>RUB</span>
                            </div>
                            <div class="buy_button">
                                <a href="{% url 'product' item.product.id %}">Buy!</a>
                            </div>
                        </div>
                    </a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}